---
- name: Déploiement et configuration RDS sur le serveur broker
  hosts: SRV-RDS
  tasks:
    - name: Lancer les commandes PowerShell pour installer le rôle RDS sur le broker, le lier à l'Active Directory, créer le certificat RDS
      ansible.windows.win_powershell:
        script: |
          Add-WindowsFeature RDS-RD-Server
          Import-Module RemoteDesktop

    - name: Configuration du broker
        win_shell:
          New-RDSessionDeployment -ConnectionBroker srv-test-ad-01.favb.local -SessionHost srv-test-ad-01.favb.local -WebAccessServer srv-test-ad-01.favb.local
          New-RDSessionCollection -CollectionName "RdsApps" -CollectionDescription "Collection RDS pour accéder aux applications" -ConnectionBroker srv-test-ad-01.favb.local -SessionHost srv-test-ad-01.favb.local
          Set-RDSessionCollectionConfiguration -CollectionName "RdsApps" -TemporaryFoldersPerSession $false -TemporaryFoldersDeletedOnExit $false
          Set-RDSessionCollectionConfiguration -CollectionName "RdsApps" -DisconnectedSessionLimitMin 360 -IdleSessionLimitMin 120
          New-RDRemoteApp -Alias Wordpad -DisplayName WordPad -FilePath "C:\Program Files\Windows NT\Accessoires\wordpad.exe" -ShowInWebAccess 1 -CollectionName "RdsApps" -ConnectionBroker srv-test-ad-01.favb.local
          New-RDRemoteApp -Alias WinSCP -DisplayName WinSCP -FilePath "C:\Program Files (x86)\WinSCP\WinSCP.exe" -ShowInWebAccess 1 -CollectionName "RdsApps" -ConnectionBroker srv-test-ad-01.favb.local
          Set-RDCertificate -Role RDS-RD-SERVER -ImportPath "C:\Users\Administrateur\Documents\rds_certificat.pfx" -Password (ConvertTo-SecureString -String "test@123" -AsPlainText -Force)
          New-RDCertificate -Role RDWebAccess -DnsName "srv-test-ad-01.favb.local" -Password (ConvertTo-SecureString -String "test@123" -AsPlainText -Force) -ExportPath "C:\Users\Administrateur\Documents\rds_cert.pfx" -ConnectionBroker srv-test-ad-01.favb.local -Force

    - name: Reboot the machine with all defaults
      ansible.windows.win_reboot:

    - name: Création du certificat https dans les autorités de certificat racine de confiance
        win_shell: |
          $rootCA = New-SelfSignedCertificate -Subject "CN=FAVB"  `
          -KeyExportPolicy Exportable  `
          -KeyUsage CertSign,CRLSign,DigitalSignature  `
          -KeyLength 2048  `
          -KeyUsageProperty All  `
          -KeyAlgorithm 'RSA'  `
          -HashAlgorithm 'SHA256'  `
          -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider"  `
          -NotAfter (Get-Date).AddYears(10)
          $SelfSignCert = New-SelfSignedCertificate -Subject "CN=favb.local"  `
          -Signer $rootCA  `
          -KeyLength 2048  `
          -KeyExportPolicy Exportable  `
          -DnsName favb.local  `
          -KeyAlgorithm 'RSA'  `
          -HashAlgorithm 'SHA256'  `
          -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider"  `
          -NotAfter (Get-Date).AddDays(350)
          $certFile = Export-Certificate -Cert $SelfSignCert -FilePath C:\Users\Administrateur\Documents\rdweb.cer


    - name: Importation du certificat dans les autorités de certificat racine de confiance
        win_shell: |
          $certPath = "C:\Users\Administrateur\Documents\rdweb.cer"
          $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certPath)
          $store = New-Object System.Security.Cryptography.X509Certificates.X509Store("Root", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()

